name: Record metrics

on:
  push:
    branches:
      - master
      - "forcerecord-*"
  schedule:
    - cron: "5 19 * * *" # 12:05 Pacific time

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out sourcecred/metrics"
        uses: actions/checkout@v2
      - name: "Check out sourcecred/metrics-output"
        uses: actions/checkout@v2
        with:
          repository: "sourcecred/metrics-output"
          path: "output"
          fetch-depth: 1
          ssh-key: ${{ secrets.METRICS_OUTPUT_DEPLOY_KEY }}
      - uses: actions/setup-node@v2.1.1
      - run: yarn
      - run: yarn build
      - name: "Collect metrics"
        run: node ./bin/main ./output
        env:
          SOURCECRED_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Commit metrics changes"
        run: |
          git -C output config user.name 'credbot'
          git -C output config user.email '42819382+credbot@users.noreply.github.com'
          git -C output add .
          git -C output commit --allow-empty -m "Update metrics: $(date -u -Is)"
      - name: "Preview committed changes"
        run: git -C output show
      - name: "Push changes (with dry-run)"
        run: git -C output push --dry-run
