name: Record metrics

on:
  push:
    branches:
      - master
      - "forcerecord-*"
  schedule:
    - cron: "5 19 * * *" # 12:05 Pacific time

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "sourcecred/metrics-output"
          path: "output"
          fetch-depth: 1
          ssh-key: ${{ secrets.METRICS_OUTPUT_DEPLOY_KEY }}
      - uses: actions/setup-node@v2.1.1
      - run: yarn
      - run: yarn build
      - run: node ./bin/main ./output
        env:
          SOURCECRED_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git -C output add .
      - name: Configure Git author as CredBot
        run: |
          git -C output config user.name 'credbot'
          git -C output config user.email '42819382+credbot@users.noreply.github.com'
      - run: git -C output commit --allow-empty -m 'Update metrics'
      - run: git -C output show
      - run: git -C output push --dry-run
